# Generated by Django 3.0.7 on 2020-06-30 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recuring', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('D', 'Daily')], max_length=100)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.TextField(null=True)),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='expenses.Expense')),
            ],
            options={
                'db_table': 'bills',
            },
        ),
    ]
