# Generated by Django 3.0.7 on 2020-07-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200630_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='remarks',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('D', 'daily'), ('W', 'weekly'), ('M', 'monthly'), ('Y', 'yearly')], default='M', max_length=100),
        ),
    ]
