# Generated by Django 3.0.7 on 2020-06-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200630_2133'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='inventory.Product'),
        ),
    ]
