# Generated by Django 3.0.7 on 2020-06-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('sales', '0002_auto_20200630_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee'),
        ),
    ]
