# Generated by Django 3.0.7 on 2020-06-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200629_1139'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='servicecategory',
            table='services',
        ),
    ]
